---
title: "Issue de l'HAD"
---

```{r}
#| label: setup3

rm(list = ls())
#
library(corrplot)
library(readODS)
library(baseph)
# library(GGally)
library(ggsci)
# library(ggstats)
library(tidyverse)
library(missMDA)
library(FactoMineR)
library(factoextra)
library(nnet)
library(kableExtra)
library(gtsummary)
# library(DataExplorer)
# library(colorspace)
# library(forestmodel)
library(janitor)
# library(fmsb)
library(labelled)
#
classeur <- "htahad.ods"
expx <- FALSE
if (expx) {
  file.create(classeur)
  file.remove(classeur)
  write_ods(iris, classeur)
}

# sessionInfo()
theme_gtsummary_language(language = "fr", decimal.mark = ",")
# theme_gtsummary_journal(journal = "jama")
options(OutDec = ",")
ptest <- list(all_continuous() ~ "wilcox.test", all_categorical() ~ "chisq.test")
load("datas/htahad.RData")
```

On recherche des facteurs éventuels pouvant influencer l'issue de l'HAD.

```{r}
#| label: tbl-isssuepop
#| tbl-cap: Issue selon les variables démagogiques & les antécédants

tt |>
  select(mater_origine:patho_associe, issue) |>
  tbl_summary(
    by = issue,
    missing = "no"
  ) |>
  add_n() |>
  add_p() |>
  bold_labels() |>
  modify_header(label ~ " ") |>
  pexptabph(exp = expx, nomfich = classeur, nomsheet = "popissue", lg = TRUE)
```

La conclusion de l'HAD semble surtout liée au terrain (atcd, pathologies associées...). Visiblement chaque maternité a sa propre politique de prise en charge des patientes.

```{r}
#| label: fig-ageissue
#| fig-cap: Issue de l'HAD selon l'âge

tt |>
  ggplot() +
  aes(x = issue, y = age_au_ddg, fill = issue) +
  geom_violin() +
  geom_boxplot(width = 0.2, fill = "grey90") +
  # annotate("text", x = 0.6, y = 48, label = "p = 0,3") +
  labs(
    title = "Issue de l'HAD selon l'âge",
    subtitle = "p = 0,3",
    x = "Issue de l'HAD",
    y = "Âge",
    caption = "",
    fill = ""
  ) +
  theme_light() +
  scale_fill_jama() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.title.x = element_text(size = 12),
    legend.title = element_text(size = 12),
    axis.title.y = element_text(
      size = 12,
      angle = 90,
      vjust = .5
    ),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    legend.position = "none"
  )
```



```{r}
#| label: tbl-isssueentree
#| tbl-cap: Issue selon le bilan initial

tt |>
  select(terme_dentree:classification_patho, issue) |>
  tbl_summary(
    by = issue,
    missing = "no"
  ) |>
  add_n() |>
  add_p() |>
  bold_labels() |>
  modify_header(label ~ " ") |>
  pexptabph(exp = expx, nomfich = classeur, nomsheet = "entreeissue", lg = TRUE)
```

Le type de suivi semble influer sur la sortie. 

## Analyse en régression

```{r}
#| label: tbl-regissue
#| tbl-cap: Issue de l'HAD - analyse en régression


multinom(
  issue ~
    mater_origine +
    age_au_ddg,
  data = tt
) |>
  tbl_regression(exponentiate = TRUE)
```
